#!/usr/bin/env bash
# Selene's Roblox standard library, roblox.yml, is committed because cloud
# sessions cannot generate it (Selene's HTTP client rejects their proxy).
# This compares it with a fresh `selene generate-roblox-std`, ignoring the two
# lines that record when it was generated:
#
#   tools/roblox-std.sh check [selene]    fail if they differ (CI warns)
#   tools/roblox-std.sh update [selene]   replace roblox.yml if they differ
#                                         (the weekly toolchain job)
#
# The fresh file is left in build/roblox-std/roblox.yml.
set -euo pipefail
cd "$(dirname "$0")/.."
export PATH="$PWD/build/bin:$PATH" # where tools/bootstrap-agent.sh installs

mode="${1:?usage: tools/roblox-std.sh check|update [selene]}"
selene="${2:-selene}"
case "$selene" in */*) selene="$(cd "$(dirname "$selene")" && pwd)/$(basename "$selene")" ;; esac

fresh=build/roblox-std/roblox.yml
mkdir -p "$(dirname "$fresh")"
(cd "$(dirname "$fresh")" && "$selene" generate-roblox-std)

strip() { sed -e '/^# This file was @generated by generate-roblox-std at /d' -e '/^last_updated: /d' "$1"; }
if diff -u <(strip roblox.yml 2>/dev/null) <(strip "$fresh") >build/roblox-std/diff; then
	echo "roblox.yml is current"
elif [ "$mode" = update ]; then
	cp "$fresh" roblox.yml
	echo "roblox.yml regenerated"
else
	echo "roblox.yml is missing or differs from what 'selene generate-roblox-std' generates now (diff below)." >&2
	echo "Merge the open Toolchain updates PR, run the toolchain job, or commit the roblox-std artifact of this CI run as roblox.yml." >&2
	head -n 100 build/roblox-std/diff >&2
	exit 1
fi
